### ISSUE TITLE
progressive for recalbox

### ISSUE THREAD

**Issue by Iga44** [kFYatek/tweakvec#2]
Hi!
Again with question)

Now I've experimented with recalbox and understood that activate your retropie's command _sudo python3 tweakvec.py --preset PAL60_, for recalbox i need to write just _python3 tweakvec.py --preset PAL60_ in terminal (through WinSCP) and pal 60 is activated...

But now i want to know what i need to type in terminal for recalbox  to activate progressive PAL60 as at your example.

I've typed
tvservice -c "NTSC 4:3 P"; sudo python3 /recalbox/share/system --preset PAL60; fbset -depth 8; fbset -depth 32; tvservice -s
or
tvservice -c "NTSC 4:3 P"; python3 /recalbox/share/system --preset PAL60; fbset -depth 8; fbset -depth 32; tvservice -s
or
tvservice -c "NTSC 4:3 P"; python3 --preset PAL60; fbset -depth 8; fbset -depth 32; tvservice -s

(tweakvec file located in recalbox/share/system folder)

and already  got errors:
-bash: line 10: tvservice: command not found
-bash: line 10: sudo: command not found
fbset: FBIOPUT_VSCREENINFO: Invalid argument
-bash: line 10: tvservice: command not found

![3](https://user-images.githubusercontent.com/76435104/181923236-14128def-8c1c-4290-be3e-a2e7485ed112.png)

So, what exactly should I  write correctly to run progressive through the terminal?

(I've suppose, that if just like  example "python3 tweakvec.py --preset PAL60" - worked, that and example with progressive should work , but i just need to know "how to write\ correct syntax  for command line)

Could you help me with it?

**Comment by kFYatek** [comment]
Sorry, I'm not really familiar with recalbox, but from my quick investigation it seems that `tvservice` is not installed there.

You might try setting `sdtv_mode=16` (for progressive NTSC) in `config.txt` on the SD card instead of using `tvservice`. Then you could run `sudo python3 /recalbox/share/system/tweakvec.py --preset PAL60` to switch from NTSC to PAL60.

**Comment by Iga44** [comment]
Yes, i know about sdtv_mode=16 and I've used on retropie, but in recalbox this method  has an impact on some applications ( for example duckstation make image only at quarter of screen). So i wanted make progressive exactly by means tweakvec, like in your example....

**Comment by kFYatek** [comment]
`tweakvec` only reconfigures the analog signal encoder. It can change the settings for color encoding (PAL, SECAM, NTSC etc.) but it cannot switch between 480i, 576i, 240p and 288p. That needs to be done by other means, such as `tvservice` or Kernel Mode Setting.

You might have some luck by copying `tvservice` and supplemental libraries from some other Pi distribution. But this is beyond the scope of this project, especially since I have no experience with Recalbox. I'm closing this ticket.

**Comment by Iga44** [comment]
Ok, clear.
Thanks
